---
# Create the "teleport" namespace
apiVersion: v1
kind: Namespace
metadata:
  name: teleport
  labels:
    app: teleport
  annotations:
    linkerd.io/inject: disabled
    field.cattle.io/projectId: local:applications
    scheduler.alpha.kubernetes.io/node-selector: "dedicated=srvr-node"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleport
  labels:
    app: teleport
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teleport
  template:
    metadata:
      labels:
        app: teleport
    spec:
      containers:
      - name: teleport
        image: public.ecr.aws/gravitational/teleport-distroless:18.1.4
        ports:
        - containerPort: 3025 # Auth Service
        - containerPort: 3023 # SSH Service
        - containerPort: 3080 # Web UI
        command: ["teleport", "start", "-c", "/etc/teleport/teleport.yaml"]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: teleport-config
          mountPath: /etc/teleport
          readOnly: true
      volumes:
      - name: teleport-config
        configMap:
          name: teleport-config
---
apiVersion: v1
kind: Service
metadata:
  name: teleport
spec:
  selector:
    app: teleport
  ports:
    - name: web
      port: 3080
      targetPort: 3080
    - name: ssh
      port: 3023
      targetPort: 3023
    - name: auth
      port: 3025
      targetPort: 3025
  type: ClusterIP
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: teleport-route
  namespace: teleport
  annotations:
    apisix.apache.org/timeout: "900"
    apisix.apache.org/websocket: "true"
spec:
  ingressClassName: apisix
  http:
    - name: webui
      websocket: true
      match:
        hosts:
          - teleport.app.suncoast.systems
        paths:
          - /*
      backends:
        - serviceName: teleport
          servicePort: 3080
---
# apiVersion: apisix.apache.org/v2
# kind: ApisixRoute
# metadata:
#   name: teleport-ssh-route
#   namespace: teleport
#   annotations:
#     apisix.apache.org/timeout: "900"
# spec:
#   ingressClassName: apisix
#   http:
#     - name: ssh
#       match:
#         hosts:
#           - teleport-ssh.app.suncoast.systems
#         paths:
#           - /*
#       backends:
#         - serviceName: teleport
#           servicePort: 3023

# ---
# apiVersion: apisix.apache.org/v2
# kind: ApisixRoute
# metadata:
#   name: teleport-auth-route
#   namespace: teleport
#   annotations:
#     apisix.apache.org/timeout: "900"
# spec:
#   ingressClassName: apisix
#   http:
#     - name: auth
#       match:
#         hosts:
#           - teleport-auth.app.suncoast.systems
#         paths:
#           - /*
#       backends:
#         - serviceName: teleport
#           servicePort: 3025
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport-config
data:
  teleport.yaml: |
    version: v3
    teleport:
      nodename: teleport
      data_dir: /var/lib/teleport
      storage:
        type: file
        path: /var/lib/teleport
      enabled: yes
      listen_addr: 0.0.0.0:3025
    ssh_service:
      enabled: yes
      listen_addr: 0.0.0.0:3023
    proxy_service:
      enabled: yes
      listen_addr: 0.0.0.0:3080